# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('department_type', models.CharField(choices=[('M', 'Municipal'), ('T', 'State Police'), ('S', 'Special'), ('', 'None Set')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentToOrgCrosswalk',
            fields=[
                ('org_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Department')),
            ],
        ),
        migrations.CreateModel(
            name='StopRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_id', models.TextField(blank=True, null=True)),
                ('subject_race_code', models.CharField(blank=True, choices=[('A', 'Asian/Pacific Islander'), ('B', 'Black'), ('I', 'Indian American / Alaskan Native'), ('W', 'White'), ('', 'No Data Available')], max_length=1, null=True)),
                ('subject_ethnicity_code', models.CharField(blank=True, choices=[('H', 'Hispanic'), ('M', 'Middle Eastern'), ('N', 'Not Applicable'), ('', 'No Data Available')], max_length=1, null=True)),
                ('subject_sex_code', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('', 'No Data Available')], max_length=1, null=True)),
                ('subject_age', models.IntegerField(blank=True, null=True)),
                ('state_resident', models.NullBooleanField()),
                ('town_resident', models.NullBooleanField()),
                ('intervention_location', models.TextField(blank=True, null=True)),
                ('stop_reason_code', models.CharField(blank=True, choices=[('I', 'Investigation, Criminal'), ('V', 'Violation, Motor Vehicle'), ('E', 'Equipment, Motor Vehicle'), ('', 'No Data Available')], max_length=1, null=True)),
                ('technique_code', models.CharField(blank=True, max_length=1, null=True)),
                ('towed', models.NullBooleanField()),
                ('statute_id', models.TextField(blank=True, null=True)),
                ('statutory_reason_for_stop', models.TextField(blank=True, null=True)),
                ('statutory_citation_post_stop', models.TextField(blank=True, null=True)),
                ('searched', models.NullBooleanField()),
                ('search_authorization_code', models.CharField(blank=True, choices=[('C', 'Consent'), ('I', 'Inventory'), ('O', 'Other'), ('N', 'Not Applicable'), ('', 'No Data Available')], max_length=1, null=True)),
                ('contraband_found', models.NullBooleanField()),
                ('custodial_arrest', models.NullBooleanField()),
                ('intervention_disposition_code', models.CharField(blank=True, choices=[('U', 'Uniform Arrest Report'), ('M', 'Misdemeanor Summons'), ('I', 'Infraction Ticket'), ('W', 'Written Warning'), ('V', 'Verbal Warning'), ('N', 'No Disposition'), ('', 'No Data Available')], max_length=1, null=True)),
                ('intervention_datetime', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.DepartmentToOrgCrosswalk')),
            ],
        ),
    ]
