# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_homepage_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='teaser',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
